### ISSUE TITLE
Getting auth error

### ISSUE THREAD

**Issue by asebak** [stalker314314/DocumentDBCpp#8] opened 2017-11-10 21:37 UTC
{message_=L"The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'ge... }
Any ideas?  Used it in C# and same code works fine.

**Comment by asebak** [comment] 2017-11-11 08:37
The create database and create collection methods work.  This error is comming from the GetDatabase method.

**Comment by asebak** [comment] 2017-11-11 21:09
looks like you need to pass resource id instead of the id, would make it easier if we can just pass the id to do a query.

**Comment by stalker314314** [comment] 2017-11-11 22:59
Thanks for reporting and probably figuring this out! Where is GetDatabase failing? in your code or in test.cpp (in project)? In project, resource_id is given in GetDatabase call: https://github.com/stalker314314/DocumentDBCpp/blob/master/test/test.cpp#L181. If you have patch/push request, feel free to send it my way!

**Comment by stalker314314** [comment] 2017-11-21 14:31
I took a more detailed look. All getters are using resource_id, this is (in my thinking) because resource_id is only unique thing here, you cannot get database by id as you may have more than one at the same time. I will close this as "by design". CosmosDB API simply doesn't have option to get DB by ID, only by resource_id

**Closed as completed by stalker314314** 2017-11-21 14:31 UTC
